import { Photo } from '@/typings';

export const galleryPhotos: Photo[] = [
  {
    id: '0',
    alt:
      'Koncert w kościele. Zespół ubrany na czarno, kobiety z czerwonymi koralami.',
    path: '/images/gallery/img1.avif',
    path_f: '/images/gallery/img1_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '1',
    alt:
      'Zespół stoi ustawiony na kształt litery V. Jedna polowa ma czarne a druga białe koszulki.',
    path: '/images/gallery/img2.avif',
    path_f: '/images/gallery/img2_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '2',
    alt: 'Zespół siedzący na schodach przed pensjonatem.',
    path: '/images/gallery/img3.avif',
    path_f: '/images/gallery/img3_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '3',
    alt:
      'Zespół przed koncertem. Chórzyści cali na czarno, chórzystki na czarnych sukniach mają kolorowe kokardy.',
    path: '/images/gallery/img4.avif',
    path_f: '/images/gallery/img4_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '4',
    alt: 'Zespół pozujący w trakcie próby w podziemiach szpitala.',
    path: '/images/gallery/img5.avif',
    path_f: '/images/gallery/img5_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '5',
    alt: 'Zespół w trakcie jesiennych warsztatów. W tle widać las.',
    path: '/images/gallery/img6.avif',
    path_f: '/images/gallery/img6_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '6',
    alt: 'Zespół w trakcie wiosennych warsztatów w Lanckoronie.',
    path: '/images/gallery/img7.avif',
    path_f: '/images/gallery/img7_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '7',
    alt:
      'Zespół przed koncertem w Rzeszowie. Całe czarne stroje, kobiety z czerwonymi koralami.',
    path: '/images/gallery/img8.avif',
    path_f: '/images/gallery/img8_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '8',
    alt: 'Koncert bożonarodzeniowy w kościele.',
    path: '/images/gallery/img9.avif',
    path_f: '/images/gallery/img9_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '9',
    alt:
      'Zespół przed jednym z koncertów, ubrany na czarno, stojący na zielonej trawie',
    path: '/images/gallery/img10.avif',
    path_f: '/images/gallery/img10_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '10',
    alt: 'Zespół w kościele Bonifratrów obok baneru z napisem ars cameralis',
    path: '/images/gallery/img11.avif',
    path_f: '/images/gallery/img11_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '11',
    alt: 'Zespół mający za sobą bazylikę archikatedralną we Fromborku.',
    path: '/images/gallery/img12.avif',
    path_f: '/images/gallery/img12_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '12',
    alt:
      'Zespół robiący sobie zdjęcie telefonem mający za sobą wody zalewu wiślanego.',
    path: '/images/gallery/img13.avif',
    path_f: '/images/gallery/img13_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '13',
    alt:
      'Zespół po koncercie w bazylice archikatedralnej we Fromborku w strojach galowych.',
    path: '/images/gallery/img14.avif',
    path_f: '/images/gallery/img14_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '14',
    alt:
      'Zdjęcie z warsztatów realizowanych w ramach programu "Małopolskie Chóry - Małopolska Rozśpiewana"',
    path: '/images/gallery/img15.avif',
    path_f: '/images/gallery/img15_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '15',
    alt:
      'Zdjęcie z warsztatów realizowanych w ramach programu "Małopolskie Chóry - Małopolska Rozśpiewana". W tle baner z logiem województwa małopolskiego.',
    path: '/images/gallery/img16.avif',
    path_f: '/images/gallery/img16_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '16',
    alt:
      'Zdjęcie z warsztatów realizowanych w ramach programu "Małopolskie Chóry - Małopolska Rozśpiewana". Uczestnicy warsztatów ubrani na czarno i biało, machają do obiektywu.',
    path: '/images/gallery/img17.avif',
    path_f: '/images/gallery/img17_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '17',
    alt:
      'Chórzyści po zakończonych warsztatach siedzą na schodach Gościńca pod Lubomirem.',
    path: '/images/gallery/img18.avif',
    path_f: '/images/gallery/img18_f.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
];

export const galleryMiniatures: Photo[] = [
  {
    id: '0',
    alt:
      'Koncert w kościele. Zespół ubrany na czarno, kobiety z czerwonymi koralami.',
    path: '/images/gallery/img1.avif',
    path_f: '/images/gallery/img1_f.webp',
    path_thumb: '/images/thumbs/img1_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '1',
    alt:
      'Zespół stoi ustawiony na kształt litery V. Jedna polowa ma czarne a druga białe koszulki.',
    path: '/images/gallery/img2.avif',
    path_f: '/images/gallery/img2_f.webp',
    path_thumb: '/images/thumbs/img2_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '2',
    alt: 'Zespół siedzący na schodach przed pensjonatem.',
    path: '/images/gallery/img3.avif',
    path_f: '/images/gallery/img3_f.webp',
    path_thumb: '/images/thumbs/img3_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '3',
    alt:
      'Zespół przed koncertem. Chórzyści cali na czarno, chórzystki na czarnych sukniach mają kolorowe kokardy.',
    path: '/images/gallery/img4.avif',
    path_f: '/images/gallery/img4_f.webp',
    path_thumb: '/images/thumbs/img4_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '4',
    alt: 'Zespół pozujący w trakcie próby w podziemiach szpitala.',
    path: '/images/gallery/img5.avif',
    path_f: '/images/gallery/img5_f.webp',
    path_thumb: '/images/thumbs/img5_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '5',
    alt: 'Zespół w trakcie jesiennych warsztatów. W tle widać las.',
    path: '/images/gallery/img6.avif',
    path_f: '/images/gallery/img6_f.webp',
    path_thumb: '/images/thumbs/img6_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '6',
    alt: 'Zespół w trakcie wiosennych warsztatów w Lanckoronie.',
    path: '/images/gallery/img7.avif',
    path_f: '/images/gallery/img7_f.webp',
    path_thumb: '/images/thumbs/img7_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '7',
    alt:
      'Zespół przed koncertem w Rzeszowie. Całe czarne stroje, kobiety z czerwonymi koralami.',
    path: '/images/gallery/img8.avif',
    path_f: '/images/gallery/img8_f.webp',
    path_thumb: '/images/thumbs/img8_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '8',
    alt: 'Koncert bożonarodzeniowy w kościele.',
    path: '/images/gallery/img9.avif',
    path_f: '/images/gallery/img9_f.webp',
    path_thumb: '/images/thumbs/img9_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '9',
    alt:
      'Zespół przed jednym z koncertów, ubrany na czarno, stojący na zielonej trawie',
    path: '/images/gallery/img10.avif',
    path_f: '/images/gallery/img10_f.webp',
    path_thumb: '/images/thumbs/img10_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '10',
    alt: 'Zespół w kościele Bonifratrów obok baneru z napisem ars cameralis',
    path: '/images/gallery/img11.avif',
    path_f: '/images/gallery/img11_f.webp',
    path_thumb: '/images/thumbs/img11_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '11',
    alt: 'Zespół mający za sobą bazylikę archikatedralną we Fromborku.',
    path: '/images/gallery/img12.avif',
    path_f: '/images/gallery/img12_f.webp',
    path_thumb: '/images/thumbs/img12_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '12',
    alt:
      'Zespół robiący sobie zdjęcie telefonem mający za sobą wody zalewu wiślanego.',
    path: '/images/gallery/img13.avif',
    path_f: '/images/gallery/img13_f.webp',
    path_thumb: '/images/thumbs/img13_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '13',
    alt:
      'Zespół po koncercie w bazylice archikatedralnej we Fromborku w strojach galowych.',
    path: '/images/gallery/img14.avif',
    path_f: '/images/gallery/img14_f.webp',
    path_thumb: '/images/thumbs/img14_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '14',
    alt:
      'Zdjęcie z warsztatów realizowanych w ramach programu "Małopolskie Chóry - Małopolska Rozśpiewana"',
    path: '/images/gallery/img15.avif',
    path_f: '/images/gallery/img15_f.webp',
    path_thumb: '/images/thumbs/img15_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '15',
    alt:
      'Zdjęcie z warsztatów realizowanych w ramach programu "Małopolskie Chóry - Małopolska Rozśpiewana". W tle baner z logiem województwa małopolskiego.',
    path: '/images/gallery/img16.avif',
    path_f: '/images/gallery/img16_f.webp',
    path_thumb: '/images/thumbs/img16_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '16',
    alt:
      'Zdjęcie z warsztatów realizowanych w ramach programu "Małopolskie Chóry - Małopolska Rozśpiewana". Uczestnicy warsztatów ubrani na czarno i biało, machają do obiektywu.',
    path: '/images/gallery/img17.avif',
    path_f: '/images/gallery/img17_f.webp',
    path_thumb: '/images/thumbs/img17_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
  {
    id: '17',
    alt:
      'Chórzyści po zakończonych warsztatach siedzą na schodach Gościńca pod Lubomirem.',
    path: '/images/gallery/img18.avif',
    path_f: '/images/gallery/img18_f.webp',
    path_thumb: '/images/thumbs/img18_thumb.webp',
    type: 'image/avif',
    type_f: 'image/webp',
  },
];
