import { Photo } from '@/typings';

export const conductorPhoto: Photo = {
  id: '1',
  path: '/images/conductor.avif',
  alt: 'Portret dyrygentki w czarnej sukni i batutą w dłoni',
  path_f: '/images/conductor_f.webp',
  path_thumb: '/images/thumbs/conductor_thumb.webp',
  type: 'image/avif',
  type_f: 'image/webp',
};

export const paragraph1: string = `Anna Sułkowska-Migoń urodziła się w Krakowie. Swoją przygodę z muzyką rozpoczęła w szkole podstawowej grając na skrzypcach. Jako instrumentalistka ukończyła studia magisterskie, specjalność altówka, na Uniwersytecie Muzycznym Fryderyka Chopina w klasie prof. dr. hab. Piotra Reicherta i dr hab. Katarzyny Budnik (2019). W trakcie studiów była uczestniczką stypendium zespołu kameralnego w Arkansas State University w Jonesboro (USA) oraz laureatką, wraz z sekstetem, pierwszego miejsca na III Ogólnopolskim Turnieju Kameralnym organizowanym w Bydgoszczy. W 2019 roku ukończyła studia licencjackie na kierunku dyrygentura symfoniczno-operowa w klasie dr. hab. Piotra Sułkowskiego w Akademii Muzycznej w Bydgoszczy. Obecnie jest studentką studiów magisterskich Akademii Muzycznej im. Krzysztofa Pendereckiego w Krakowie na dwóch kierunkach: dyrygentura symfoniczna w klasie dr. hab. Łukasza Borowicza oraz edukacja artystyczna w zakresie sztuki muzycznej, specjalność dyrygentura chóralna w klasie prof. dr hab. Lidii Matynian i dr. Andrzeja Korzeniowskiego.`;
export const paragraph2: string = `Jest inicjatorką wielu inicjatyw społecznych. Jako instruktorka Związku Harcerstwa Rzeczypospolitej nie tylko zajmowała się organizacją obozów, lecz również dbała o propagowanie kultury muzycznej wśród młodzieży. Jest pomysłodawczynią i koordynatorką projektu „Harcerska piosnka” – płyty wydanej z okazji Roku Harcerstwa w Polsce (2018) z piosenkami harcerskimi zaaranżowanymi w nowej, jazzowej odsłonie; projekt był współfinansowany przez Narodowe Centrum Kultury. W Krakowie, w teatrze Variété, dwukrotnie zorganizowała koncert „Harcerskie Jazzy” (2018, 2019) współrealizowany przez Narodowe Centrum Kultury i Urząd Marszałkowski Województwa Małopolskiego. W 2019 roku współpracowała przy tworzeniu programu Magdaleny Miśki-Jackowskiej w RMF Classic pt. „Zagraj to jeszcze raz”, który był poświęcony muzyce filmowej. W sezonie 2020/2021 była stypendystką programu Instytutu Muzyki i Tańca „Dyrygent-Rezydent” asystując i dyrygując w Filharmonii Dolnośląskiej w Jeleniej Górze. Prowadziła już orkiestry, takie jak: Filharmonii Warmińsko-Mazurskiej, Filharmonii Dolnośląskiej, Kameralną Orkiestrę Akademii Muzycznej w Krakowie (w trakcie 7. Krakowskiej Wiosny Wiolonczelowej). W marcu 2021 asystowała Maestro Antoniemu Witowi podczas koncertu realizowanego w Filharmonii Krakowskiej. Poza chórem Ars Cameralis prowadzi chór Akademii Ignatianum w Krakowie oraz szkolny chór Państwowej Szkoły Muzycznej I st. w Olkuszu.`;
